config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages, dependent: :destroy
	broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ new create ]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private
    def set_room
      @room = Room.find(params[:room_id])
    end

    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.create!(room_params)
    redirect_to @room, notice: 'Room was successfully created.'
  end

  def update
    @room.update!(room_params)
    redirect_to @room, notice: 'Room was successfully updated.'
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatapp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_message.html.haml
%p{id: "#{dom_id message}"} 
	#{message.created_at.to_s(:short)} : #{message.content}

app/views/messages/create.turbo_stream.erb
<% # Return handled by cable %>

app/views/messages/new.html.haml
%h1 New Message

= turbo_frame_tag "new_message", target: "_top" do 
  = form_with(model: [ @message.room, @message ], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |form| 
    = form.text_field :content, placeholder: "Type a message", class: "form-control"
    = form.submit "Send", data: { disable_with: false }, class: "btn btn-primary", role: "button"
    
= link_to 'Back', @message.room 

app/views/rooms/_form.html.haml
= form_with(model: room) do |form| 
  .field
    = form.label :name 
    = form.text_field :name 

  .actions
    = form.submit 
  

app/views/rooms/_room.html.haml
%div{id: "#{dom_id room}"}
	= room.name

app/views/rooms/edit.html.haml
%h1 Editing Room

= turbo_frame_tag "room" do 
  = render 'form', room: @room 

%p #{link_to 'Show', @room} | #{link_to 'Back', rooms_path}

app/views/rooms/index.html.haml
%p{id: "notice"} #{notice}

%h1 Rooms

%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"}
  %tbody
    - @rooms.each do |room|
      %tr
        %td #{room.name}
        %td #{link_to 'Show', room}
        %td #{link_to 'Edit', edit_room_path(room)}
        %td #{link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }}
= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New Room

= render 'form', room: @room

= link_to 'Back', rooms_path 

app/views/rooms/show.html.haml
.container-fluid.p-4.h-100
	.h-100.p-4.border.border-dark.rounded-lg.p-4{style: "position: relative"}
		= turbo_stream_from @room 

		= turbo_frame_tag "room" do 
			.w-100.m-0.border.border-dark
				.row.m-0
					.col-md-1.p-0.border.border-dark
						= link_to 'Back', rooms_path, "data-turbo-frame": "_top", class: "btn btn-primary", role: "button"
					.col-md-10.p-0.border.border-dark
						= render @room 
					.col-md-1.p-0.text-right.border.border-dark
						= link_to 'Edit', edit_room_path(@room), class: "btn btn-primary", role: "button"
			 
			#messages
				= render @room.messages
			


		.w-100.p-4.border.border-dark{style: "position: absolute; bottom: 0; left: 0;"}
			= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top"